name: Build and Deploy
run-name: Build and deploy by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Clean install of dependencies
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Deploy to firebase hosting
        uses: w9jds/firebase-action@v14.7.0
        with:
          args: deploy --only hosting
        env: 
          GCP_SA_KEY: ${{ env.GCP_SA_KEY }}
